version: 2.1
jobs:
  create_and_deploy_front_end:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: |
          aws cloudformation deploy \
            --template-file bucket.yml \
            --stack-name "stk-$CIRCLE_WORKFLOW_ID" \
            --parameter-overrides NAME="$CIRCLE_WORKFLOW_ID"
      - run: aws s3 sync . s3://"$CIRCLE_WORKFLOW_ID" --delete
      
  get_last_deployment_id:
     docker:
       - image: amazon/aws-cli
       - image: circleci/node:13.8.0
     steps:
       - run: |
           aws cloudformation describe-stacks \
           --query Stacks[].Outputs[?OutputKey=='PipelineID'].OutputValue \
           --output text > ~/id.txt
       - persist_to_workspace:
          root: ~/
          paths:
            - id.txt


  promote_to_production:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: |
          aws cloudformation deploy \
            --template-file cloudfront.yml \
            --stack-name cloudfront \
            --parameter-overrides PipelineID="$CIRCLE_WORKFLOW_ID"
  
  clean_up_old_front_end:  
      docker:
      - image: amazon/aws-cli
      - image: circleci/node:13.8.0
      steps:
      - attach_workspace:
            at: ~/
      - run: cat ~/id.txt

workflows:
   default:
      jobs:
         - create_and_deploy_front_end
         - get_last_deployment_id:
             requires:
               - create_and_deploy_front_end
         - promote_to_production:
             requires:
               - get_last_deployment_id
         - clean_up_old_front_end:
              requires:
               - promote_to_production
