---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "open the server1"
  become: yes
  shell: |
   curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
  
- name: "open the server2"
  become: yes
  shell: |
   sudo apt-get install -y nodejs
   
- name: "open the server3"
  become: yes
  shell: |
   sudo apt-get -y install build-essential
   
- name: "open the server4"
  copy:
     src: index.js
     dest: /home/ubuntu/index.js
     backup: yes
     
- name: "open the server5"
  become: yes
  shell: |
   node index.js
